version: '3'


services:
  web:
    build: angular
    ports:
      - "8080:80"
    networks:
      - web
   

  server:
    build: server
    restart: always
    depends_on:
      - db
    volumes:
      - ./images:/images
    networks:
      - bd
      - web
    environment:
       DB_PASSWORD: /run/secrets/db_root_password
       DB_USER: /run/secrets/db_user_password
       DB_PORT: 3306
       DB_HOST: db
       TOKEN_PASSWORD: /run/secrets/token_password
    secrets:
      - db_root_password
      - db_user_password
      - token_password
  

  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/dsdsd  #root 
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    #command: ["mysql", "-u", "root", "-p", "root", "-e", "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'root'"]
    volumes:
      #- /home/ciber2/ciber/db2:/var/lib/mysql
     - ./db:/var/lib/mysql
     # mysql -u root -p
     #GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'root';
    networks:
      - bd
    

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
  
  apache-waf:
    build: waf
    ports:
      - 9095:80 
    networks:
      - web
    

networks:
  bd:
    driver: bridge
  web:
    driver: bridge



secrets:
  db_root_password:
    file: ./secretos/db_root_password.txt
  db_user_password:
    file: ./secretos/db_user_password.txt
  token_password:
    file: ./secretos/token_password.txt


