version: '3'

services:
  web:
    build: angular
    ports:
      - "8080:80"

  server:
    build: server
    restart: always
    depends_on:
      - db
    volumes:
      - ./images:/images

  

  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    #command: ["mysql", "-u", "root", "-p", "root", "-e", "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'root'"]
    volumes:
      #- /home/ciber2/ciber/db2:/var/lib/mysql
     - ./db:/var/lib/mysql
     # mysql -u root -p
     #GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'root';


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
  
  apache-waf:
    build: waf
    ports:
      - 9095:80 