version: '3'

services:
  web:
    build: angular
    ports:
      - "8080:80"

  server:
    build: server
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      - db

  

  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_HOST: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      #- /home/ciber2/ciber/db:/var/lib/mysql
     - H:\MisDocumentos\documentos\proyectos\proyecto-peps2\db:/var/lib/mysql
     # mysql -u root -p
     #GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'root';


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db