version: '3'


services:
  web:
    build: angular
    restart: always
    networks:
      - web
   

  server:
    build: server
    restart: always
    depends_on:
      - db
    volumes:
      - ./images:/images
    networks:
      - bd
      - waf-api
    environment:
       DB_PASSWORD: root #/run/secrets/db_root_password
       DB_USER: root #/run/secrets/db_root_user
       DB_PORT: 3306
       DB_HOST: db
       TOKEN_PASSWORD: LDR_PEPS #/run/secrets/token_password
    secrets:
      - db_root_password
      - db_root_user
      - token_password
  

  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/db_root_password  #root 
      MYSQL_USER: /run/secrets/db_user_username
      MYSQL_PASSWORD: /run/secrets/db_user_password
    #command: ["mysql", "-u", "root", "-p", "root", "-e", "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'root'"]
    volumes:
      #- /home/ciber2/ciber/db2:/var/lib/mysql
     - ./db:/var/lib/mysql
     # mysql -u root -p
     #GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'root';
    networks:
      - bd
    secrets:
      - db_root_password
      - db_user_username
      - db_user_password



  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9090:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    networks:
      - bd
  
  apache-waf:
    build: waf
    ports:
      - 5000:5000
      - 8080:8080
    networks:
      - web
      - waf-api
    

networks:
  bd:
    driver: bridge
  web:
    driver: bridge
  waf-api:
    driver: bridge


secrets:
  db_root_user:
    file: ./secretos/db_root_user.txt
  db_root_password:
    file: ./secretos/db_root_password.txt
  db_user_username:
    file: ./secretos/db_user_username.txt
  db_user_password:
    file: ./secretos/db_user_password.txt
  token_password:
    file: ./secretos/token_password.txt


